gText_Birch_Welcome::
	.string "Hi there!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Professor Juniper.\n"
	.string "Everyone calls me the Pokémon Professor!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "That's right! This world is widely\n"
	.string "inhabited by mysterious creatures\l"
	.string "Called Pokémon!\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Pokémon have mysterious powers.\n"
	.string "They come in many shapes\l"
	.string "and live in many different places.\p"
	.string "We humans live happily with Pokémon!\n"
	.string "Living and working together,\l"
	.string "we complement each other.\p"
	.string "We help each other out to\n"
	.string "accomplish difficult tasks.\p"
	.string "Having Pokémon battle one another\n"
	.string "is particularly popular, and it deepens\l"
	.string "the bonds between people and Pokémon.\l"
	.string "And that is why I research Pokémon.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Well, that's enough from me...\n"
	.string "Could you tell me about yourself?\p"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?\p"
	.string "$"

gText_Birch_WhatsYourName::
	.string "I'd like to know your name.\p"
	.string "Please tell me.\p"
	.string "$"

gText_Birch_SoItsPlayer::
	.string "Your name is {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "So your name's {PLAYER}{KUN}.\n"
	.string "What a wonderful name!\p"
	.string "Well then. I'm going to introduce you\n"
	.string "to your two best friends!\p"
	.string "$"

gText_Birch_MeetCheren::
	.string "This young man is Cheren.\p"
	.string "He can be a little difficult, but\n"
	.string "he's a very honest person.\p"
	.string "$"

gText_Birch_MeetBianca::
	.string "This young woman is Bianca.\p"
	.string "She's a little flighty,\n"
	.string "but she works very hard.\p"
	.string "$"

gText_Birch_AllTogether::
	.string "I think you three have potential,\n"
	.string "so I'm going to give you\l"
	.string "a very, very important Pokémon.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}{KUN}!\p"
	.string "The moment you choose the\n"
	.string "Pokémon that will accompany\l"
	.string "you on your journey,\l"
	.string "your story will truly begin.\p"
	.string "During your journey, you will meet many\n"
	.string "Pokémon and people with different\l"
	.string "personalities and points of view!\p"
	.string "I really hope you find what is important\n"
	.string "to you in all of these travels...\p"
	.string "That's right! Befriend\n"
	.string "new people and Pokémon and\l"
	.string "grow as a person!\p"
	.string "That is the most important goal\n"
	.string "for your journey!\p"
	.string "Let's go visit the world of Pokémon!\p"
	.string "$"
